on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

name: features

jobs:
  test:
    name: Rumqtt build and test
    runs-on: [self-hosted, linux, X64, rumqtt]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features


